{% set name = "unifhy" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/unifhy-org/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7500053ed50fad1775d88f4c9065a9de859ad0a5f071bf480d605eaa5cb142a0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cf-python >=3.11.0
    - cftime
    - cfunits
    - esmpy
    - netcdf4 >=1.5
    - numpy >=1.16
    - pyproj >=3.0
    - python >={{ python_min }}
    - pyyaml >=5.3

test:
  imports:
    - unifhy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/unifhy/
  summary: Unified Framework for Hydrology
  description: |
    The Python package unifhy (Unified Framework for Hydrology) is a hydrological modelling framework 
    which combines interchangeable modelling components for the surface layer, subsurface, and open water 
    parts of the terrestrial water cycle. It is designed to foster collaborations between land surface, 
    hydrological, and groundwater modelling communities.
  license: BSD-3-Clause
  license_file: LICENCE.rst
  doc_url: https://unifhy-org.github.io/unifhy/
  dev_url: https://github.com/unifhy-org/unifhy

extra:
  recipe-maintainers:
    - ThibHlln
